### ISSUE TITLE
Data import functionality

### ISSUE THREAD

**Issue by chris-prener** [shaughnessyar/driftR#10]
The current `dr_readSonde` functionality and the two new read functions for EXO and HOBO devices should be folded into a single `dr_read()` function. We'll have to retain `dr_readSonde` as a working function for now - will need to return a message telling users that the function has been deprecated and will be removed at a later date.

**Comment by shaughnessyar** [comment]
Hi Chris, `dr_read()` should be ready to go.

**Comment by chris-prener** [comment]
OK awesome @shaughnessyar - want to push your changes to the branch and open up a pull request?
