### ISSUE TITLE
Updates to README

### ISSUE THREAD

**Issue by chris-prener** [shaughnessyar/driftR#16]
We should: 

- [x] add a "what's new in version 1.1" section at the top
- [x] add `dr_replace` to the example code
- [x] add discussion of the `cleanVar` to the what's new section
- [x] update the example code from `dr_readSonde` to `dr_read`
- [x] add tidyverse style lifecycle badge at `maturing`
- [x] remove any reference to the `format` argument in `dr_factor`
- [x] update contributing section to refer to `.github/` directory

**Comment by shaughnessyar** [comment]
I updated the dr_read
