### ISSUE TITLE
Updates to the main vignette

### ISSUE THREAD

**Issue by chris-prener** [shaughnessyar/driftR#17]
We should: 

- [x] add `dr_replace` to the example code
- [x] add additional discussion of `dr_drop`
- [x] update the example code from `dr_readSonde` to `dr_read`
- [x] add additional discussion of `dr_read`
- [x] remove any reference to the `format` argument in `dr_factor`

**Comment by shaughnessyar** [comment]
I got the last three bullets done.

**Comment by shaughnessyar** [comment]
Actually, I need to work on the discussion of `dr_read` some more. I forgot about the cleaning variable names.
