### ISSUE TITLE
Deprecate dr_readSonde

### ISSUE THREAD

**Issue by chris-prener** [shaughnessyar/driftR#24]
Once we have `dr_read()` up and running, we should deprecate `dr_readSonde` - advice on how to do so is here: http://r-pkgs.had.co.nz/release.html

**Comment by shaughnessyar** [comment]
Hey, I just added the warning to deprecate dr_readSonde. Let me know what you think and then I'll open a pull request.

**Comment by chris-prener** [comment]
Looks good!

**Comment by chris-prener** [comment]
This was implemented in pull request #30
