### ISSUE TITLE
Updates to other existing vignettes

### ISSUE THREAD

**Issue by chris-prener** [shaughnessyar/driftR#26]
Check for references to: 

- [x] add `dr_replace` to the example code as appropriate
- [x] update the example code from `dr_readSonde` to `dr_read`
- [x] remove any reference to the `format` argument in `dr_factor`

**Comment by shaughnessyar** [comment]
I think I finished all of the last two bullet points.

**Comment by shaughnessyar** [comment]
Though, we might also want to increase the number of examples for `dr_drop` in the README and getting started.
