### ISSUE TITLE
Update dr_read for instrument = EXO

### ISSUE THREAD

**Issue by shaughnessyar** [shaughnessyar/driftR#45]
YSI updated their Kor software that processes the EXO data and the new file output is not compatible with `dr_read(..., instrument =  "EXO")`. We need to find a work around that keeps both structures supported. 

@chris-prener

**Comment by chris-prener** [comment]
because of course they broke the data formatting! Is there a way to parse the contents of a data file to determine whether it is an "old" EXO file or a "new" EXO file @shaughnessyar ?

**Comment by shaughnessyar** [comment]
I think so. The most obvious to me right now is that the output is a csv instead of a xlsx file, but that might not be standard for all users. I'm going to look through the structures of the old and new outputs to see if I can find a ubiquitous way to tell the difference.

**Comment by chris-prener** [comment]
ok - would be good to verify the formatting issue and check the structure!

**Comment by chris-prener** [comment]
@carly-r-finegan - do you get a `.csv` file or a `.xlsx` file now for EXO?

**Comment by carly-r-finegan** [comment]
we get a .csv file for the EXO output @chris-prener
________________________________

**Comment by chris-prener** [comment]
thanks @carly-r-finegan - as long as it is reading in, we're good to go!
