### ISSUE TITLE
dr_read() error with Exo

### ISSUE THREAD

**Issue by chris-prener** [shaughnessyar/driftR#49]
The new Exo output does not work with the current workflow. I've patched it so that `dr_read()` continues to work with the old output, but also works with the new output format.

@carly-r-finegan - can you test it? Install:

```r
install.packages("remotes")
```

then

```r
remotes::install_github("shaughnessyar/driftR", ref = "exo-probs")
```

From there, you should be able to use `dr_read()` on your data!

**Comment by carly-r-finegan** [comment]
@chris-prener  I will test it this afternoon. Also, the issue with the column headings being shifted was resolved - there was an extra comma in one of the column titles.

**Comment by chris-prener** [comment]
great, thanks @carly-r-finegan !

**Comment by carly-r-finegan** [comment]
@chris-prener it works! Thanks for your help!

**Comment by chris-prener** [comment]
ok - @shaughnessyar - can you test this on some older data?

**Comment by shaughnessyar** [comment]
Yes, no problem.

**Comment by chris-prener** [comment]
hey @shaughnessyar - wanted to give this a bump! this will be a good portion of what I'm hoping t to accomplish with our update...

**Comment by shaughnessyar** [comment]
hey @chris-prener. Everything looks good for the old EXO files.

**Comment by chris-prener** [comment]
ok awesome - great to hear!
