### ISSUE TITLE
Issue with dr_correctOne

### ISSUE THREAD

**Issue by ETaylor21** [shaughnessyar/driftR#51]
---

I believe there is an issue with line 113 in the dr_correctOne function's code. Based on the vignette and Dr. Hasenmuller's dissertation, the formula for correcting drift based on a single-point calibration value is c = m+Ft*(Si-Sf). My understanding is that Si would translate to the calStd in the function and Sf would then be the calVal meaning that the code should read (calStd - calVal), however, the code is currently written as (calVal - calStd). 

![dr_correctOne_code](https://user-images.githubusercontent.com/46635621/77085129-47fe7e00-69d6-11ea-92c2-f962402d7d5e.png)

To illustrate, I ran the example code given for dr_correctOne and as you can see the actual SpCond values were corrected to a higher value following the drift correction even though the post-cal value was 1.05 so the values should have been corrected to a lower value. I manually wrote out the formula just to double-check and when running that bit of code instead, the returned corrected values were lower than the actual values as expected. 

``` r
library(driftR)
library(tidyverse)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date

testData <- data.frame(
  Date = c("9/18/2015", "9/18/2015", "9/18/2015", "9/18/2015", "9/18/2015", "9/18/2015"),
  Time = c("12:10:49", "12:15:50", "12:20:51", "12:25:51", "12:30:51", "12:35:51"),
  Temp = c(14.76, 14.64, 14.57, 14.51, 14.50, 14.63),
  SpCond = c(0.754, 0.750, 0.750, 0.749, 0.749, 0.749),
  corrFac = c(0.0000000, 0.2003995, 0.4007989, 0.6005326, 0.8002663, 1.0000000),
  stringsAsFactors = FALSE
)

dr_correctOne(testData, sourceVar = SpCond, cleanVar = SpCond_Corr,
              calVal = 1.05, calStd = 1, factorVar = corrFac)
#>        Date     Time  Temp SpCond   corrFac SpCond_Corr
#> 1 9/18/2015 12:10:49 14.76  0.754 0.0000000   0.7540000
#> 2 9/18/2015 12:15:50 14.64  0.750 0.2003995   0.7600200
#> 3 9/18/2015 12:20:51 14.57  0.750 0.4007989   0.7700399
#> 4 9/18/2015 12:25:51 14.51  0.749 0.6005326   0.7790266
#> 5 9/18/2015 12:30:51 14.50  0.749 0.8002663   0.7890133
#> 6 9/18/2015 12:35:51 14.63  0.749 1.0000000   0.7990000

as.numeric(testData$SpCond)+as.numeric(testData$corrFac)*(1-1.05)
#> [1] 0.7540000 0.7399800 0.7299601 0.7189734 0.7089867 0.6990000
```

<sup>Created on 2020-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```

**Comment by chris-prener** [comment]
@shaughnessyar - can you check this out, please?

**Comment by shaughnessyar** [comment]
@chris-prener yes, this is the issue of the negative sign that I mentioned. I have a branch right now that already corrects that mistake. We just need to get the change to pass the checks and then we can merge the branch.

**Comment by chris-prener** [comment]
Ah sorry - I had forgotten about this. Refresh my memory - what checks are failing right now?

**Comment by shaughnessyar** [comment]
We had to re-write the calibration sample data and I think that made some of the checks unhappy.  Can you pull the branch and see what you get? All I could see what the build was failing

**Comment by chris-prener** [comment]
This has been fixed very, very belatedly on the `master` branch - we should have this back on CRAN soon @ETaylor21!
